// Generated by import-stickers.py - do not edit by hand.
// Add a pack folder to stickers/ and re-run the script to extend this.

export interface StickerTheme {
  id: string
  label: string
  /** Pose shown on the desk normally. */
  idle: string
  /** Pose shown when the student is marked absent - not every theme has one. */
  absent?: string
  poses: string[]
}

export const STICKER_THEMES: StickerTheme[] = [
  {
    id: 'owl',
    label: 'Owl',
    idle: 'owl',
    absent: undefined,
    poses: ['owl', 'owl-002', 'owl-003', 'owl-004', 'owl-005', 'owl-006', 'owl-007', 'owl-008', 'owl-009', 'owl-010', 'owl-011', 'owl-012', 'owl-013', 'owl-014', 'owl-016', 'owl-017', 'owl-018', 'owl-019'],
  },
  {
    id: 'cute-axolotl',
    label: 'Cute Axolotl',
    idle: 'axolotl',
    absent: undefined,
    poses: ['axolotl', 'axolotl-002', 'axolotl-003', 'axolotl-004', 'axolotl-005', 'axolotl-009', 'axolotl-011', 'axolotl-012', 'axolotl-013', 'axolotl-014', 'axolotl-015', 'axolotl-017', 'axolotl-018', 'axolotl-019'],
  },
  {
    id: 'chameleon',
    label: 'Chameleon',
    idle: 'chameleon',
    absent: undefined,
    poses: ['chameleon', 'chameleon-002', 'chameleon-003', 'chameleon-004', 'chameleon-005', 'chameleon-006', 'chameleon-007', 'chameleon-008', 'chameleon-012', 'chameleon-013', 'chameleon-014', 'chameleon-015', 'chameleon-019'],
  },
  {
    id: 'sheep',
    label: 'Sheep',
    idle: 'sheep',
    absent: undefined,
    poses: ['sheep', 'sheep-002', 'sheep-003', 'sheep-005', 'sheep-006', 'sheep-007', 'sheep-008', 'sheep-009', 'sheep-010', 'sheep-011', 'sheep-012', 'sheep-013', 'sheep-014', 'sheep-015', 'sheep-016', 'sheep-017', 'sheep-018', 'sheep-019', 'sheep-020'],
  },
  {
    id: 'doctor',
    label: 'Doctor',
    idle: 'doctor',
    absent: undefined,
    poses: ['doctor', 'doctor-002', 'doctor-003', 'doctor-007', 'doctor-008', 'doctor-012', 'doctor-013', 'doctor-014', 'doctor-015', 'doctor-016', 'doctor-017', 'doctor-018', 'doctor-019', 'doctor-020'],
  },
  {
    id: 'girl',
    label: 'Girl',
    idle: 'girl',
    absent: undefined,
    poses: ['girl', 'girl-002', 'girl-003', 'girl-005', 'girl-006', 'girl-007', 'girl-008', 'girl-009', 'girl-011', 'girl-014', 'girl-015', 'girl-016', 'girl-017', 'girl-018', 'girl-019', 'girl-020'],
  },
  {
    id: 'astronaut',
    label: 'Astronaut',
    idle: 'astronaut',
    absent: undefined,
    poses: ['astronaut', 'astronaut-002', 'astronaut-003', 'astronaut-004', 'astronaut-005', 'astronaut-006', 'astronaut-007', 'astronaut-008', 'astronaut-009', 'astronaut-010', 'astronaut-011', 'astronaut-012', 'astronaut-013', 'astronaut-014', 'astronaut-015', 'astronaut-016', 'astronaut-017', 'astronaut-018', 'astronaut-019', 'astronaut-020'],
  },
  {
    id: 'crocodile',
    label: 'Crocodile',
    idle: 'crocodile',
    absent: undefined,
    poses: ['crocodile', 'crocodile-002', 'crocodile-003', 'crocodile-004', 'crocodile-005', 'crocodile-006', 'crocodile-007', 'crocodile-008', 'crocodile-009', 'crocodile-010', 'crocodile-011', 'crocodile-013', 'crocodile-015', 'crocodile-017', 'crocodile-018', 'crocodile-019'],
  },
  {
    id: 'little-ghost',
    label: 'Little Ghost',
    idle: 'ghost-003',
    absent: undefined,
    poses: ['ghost-002', 'ghost-003', 'ghost-004', 'ghost-005', 'ghost-006', 'ghost-008', 'ghost-009', 'ghost-010', 'ghost-011', 'ghost-012', 'ghost-013', 'ghost-015', 'ghost-016', 'ghost-017', 'ghost-018', 'ghost-019', 'ghost-020'],
  },
  {
    id: 'wolf',
    label: 'Wolf',
    idle: 'wolf-009',
    absent: undefined,
    poses: ['wolf-002', 'wolf-003', 'wolf-004', 'wolf-005', 'wolf-006', 'wolf-007', 'wolf-008', 'wolf-009', 'wolf-010', 'wolf-011', 'wolf-012', 'wolf-013', 'wolf-015', 'wolf-016', 'wolf-017', 'wolf-020'],
  },
  {
    id: 'frog',
    label: 'Frog',
    idle: 'happy',
    absent: 'meditation',
    poses: ['award', 'celebration', 'cauldron', 'celebration-007', 'chocolate-bar', 'computer', 'fishing', 'graduation', 'happy', 'superhero', 'hidden', 'idea', 'vacation', 'read', 'love', 'chemistry', 'meditation', 'rainbow', 'selfie', 'happy-031', 'goal', 'winner', 'hello'],
  },
  {
    id: 'lion',
    label: 'Lion',
    idle: 'award',
    absent: 'meditation',
    poses: ['angel', 'award', 'social-media', 'cauldron', 'idea', 'in-love', 'vacation', 'in-love-016', 'celebration', 'meditation', 'read', 'vacation-023', 'selfie', 'surprise', 'goal', 'winner'],
  },
  {
    id: 'fox',
    label: 'Fox',
    idle: 'happy',
    absent: 'meditation',
    poses: ['happy', 'angel', 'award', 'social-media', 'cauldron', 'birthday', 'chemistry', 'relaxation', 'treasure', 'winter', 'fishing', 'happy-021', 'idea', 'in-love', 'in-love-025', 'celebration', 'meditation', 'read', 'santa-claus', 'selfie', 'surprise', 'spa', 'winner', 'workout-042'],
  },
  {
    id: 'raccoon',
    label: 'Raccoon',
    idle: 'happy',
    absent: 'meditation',
    poses: ['cauldron', 'experiment', 'happy', 'hug', 'happy-011', 'idea', 'food', 'meditation', 'vacation', 'rockstar', 'selfie', 'shopping', 'beach', 'surprise', 'goal'],
  },
  {
    id: 'unicorn',
    label: 'Unicorn',
    idle: 'fishing',
    absent: 'meditation',
    poses: ['social-media', 'celebration', 'cauldron', 'computer', 'rainbow', 'fishing', 'superhero', 'in-love', 'celebration-015', 'meditation', 'vacation', 'launch', 'santa-claus', 'hidden', 'selfie', 'idea', 'hello', 'computer-030'],
  },
  {
    id: 'books',
    label: 'Books',
    idle: 'book',
    absent: undefined,
    poses: ['book', 'brain', 'book-003', 'book-005', 'brain-006', 'book-007', 'book-008', 'book-009', 'book-012', 'book-014', 'book-015', 'brain-016', 'brain-017', 'brain-018', 'brain-019', 'brain-020'],
  },
  {
    id: 'anime-girl',
    label: 'Anime Girl',
    idle: 'happy',
    absent: undefined,
    poses: ['blushing', 'good', 'happy', 'hi', 'love', 'ok', 'optimist', 'peace', 'sing', 'yes'],
  },
  {
    id: 'smartphone',
    label: 'Smartphone',
    idle: 'smartphone',
    absent: undefined,
    poses: ['smartphone', 'smartphone-003', 'smartphone-004', 'smartphone-007', 'smartphone-008', 'smartphone-009', 'smartphone-010', 'smartphone-011', 'smartphone-012', 'smartphone-013', 'smartphone-014', 'smartphone-018', 'smartphone-019', 'smartphone-020'],
  },
  {
    id: 'sushi',
    label: 'Sushi',
    idle: 'sushi',
    absent: undefined,
    poses: ['sushi', 'sushi-002', 'sushi-003', 'sushi-004', 'sushi-005', 'sushi-006', 'sushi-007', 'sushi-008', 'sushi-009', 'sushi-010', 'sushi-011', 'sushi-012', 'sushi-013', 'sushi-014', 'sushi-015', 'sushi-016', 'sushi-017', 'sushi-018', 'sushi-019', 'sushi-020'],
  },
  {
    id: 'anime-boy',
    label: 'Anime Boy',
    idle: 'happy',
    absent: 'yawn',
    poses: ['blushing', 'excited', 'good', 'happy', 'hi', 'love', 'ok', 'peace', 'sing', 'yawn', 'yes'],
  },
]
