#!/usr/bin/env python3
"""Turn the raw Flaticon sticker packs in stickers/ into the app's avatar library.

Re-runnable: drop another pack folder into stickers/, run this, and the new theme
appears in the app. Copies the SVGs into public/ under tidy names and regenerates
src/lib/stickerLibrary.ts, so nothing has to be wired up by hand.
"""
import pathlib
import re
import shutil

ROOT = pathlib.Path(__file__).parent
SRC = ROOT / "stickers"
OUT = ROOT / "public" / "avatars" / "stickers"
MANIFEST = ROOT / "src" / "lib" / "stickerLibrary.ts"

# Flaticon prefixes every pack folder with its numeric asset id, and every file with
# an index - neither means anything to us.
THEME_ID = re.compile(r"^\d+-")
POSE_ID = re.compile(r"^(\d+)-")

# A pose whose name matches one of these is the one to show when a student is
# marked absent. Ordered by preference.
SLEEPY = ["sleep", "tired", "yawn", "sick", "meditation"]
# ...and these make the best resting pose on a desk.
IDLE = ["happy", "hi", "hello", "good", "ok", "peace", "optimist", "celebration"]


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def first_match(poses: list[str], wanted: list[str]) -> str | None:
    for w in wanted:
        for p in poses:
            if w in p:
                return p
    return None


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    themes = []
    for pack in sorted(d for d in SRC.iterdir() if d.is_dir()):
        svgs = sorted(pack.rglob("*.svg"))
        if not svgs:
            continue

        theme = slug(THEME_ID.sub("", pack.name))
        dest = OUT / theme
        dest.mkdir()

        poses: list[str] = []
        for f in svgs:
            stem = f.stem
            index = POSE_ID.match(stem)
            name = slug(POSE_ID.sub("", stem)) or "pose"
            # Several packs reuse a description across poses ("happy" twice); keep the
            # original index on the duplicate so both survive.
            if name in poses:
                name = f"{name}-{index.group(1) if index else len(poses)}"
            poses.append(name)
            shutil.copyfile(f, dest / f"{name}.svg")

        themes.append(
            {
                "id": theme,
                "label": theme.replace("-", " ").title(),
                "idle": first_match(poses, IDLE) or poses[0],
                "absent": first_match(poses, SLEEPY),
                "poses": poses,
            }
        )

    lines = [
        "// Generated by import-stickers.py - do not edit by hand.",
        "// Add a pack folder to stickers/ and re-run the script to extend this.",
        "",
        "export interface StickerTheme {",
        "  id: string",
        "  label: string",
        "  /** Pose shown on the desk normally. */",
        "  idle: string",
        "  /** Pose shown when the student is marked absent - not every theme has one. */",
        "  absent?: string",
        "  poses: string[]",
        "}",
        "",
        "export const STICKER_THEMES: StickerTheme[] = [",
    ]
    for t in themes:
        absent = f"'{t['absent']}'" if t["absent"] else "undefined"
        poses = ", ".join(f"'{p}'" for p in t["poses"])
        lines += [
            "  {",
            f"    id: '{t['id']}',",
            f"    label: '{t['label']}',",
            f"    idle: '{t['idle']}',",
            f"    absent: {absent},",
            f"    poses: [{poses}],",
            "  },",
        ]
    lines += ["]", ""]
    MANIFEST.write_text("\n".join(lines))

    total = sum(len(t["poses"]) for t in themes)
    with_absent = sum(1 for t in themes if t["absent"])
    print(f"{len(themes)} themes, {total} poses -> {OUT.relative_to(ROOT)}")
    print(f"{with_absent}/{len(themes)} themes have an absent pose")


if __name__ == "__main__":
    main()
